# Generated by Django 4.2.4 on 2023-08-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_groups_remove_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_invite_code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
