# Generated by Django 4.2.4 on 2023-08-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_activated_invite_code_user_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
