# Generated by Django 4.2.4 on 2023-08-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_authorization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activated_invite_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
